[settings]
pipx_uvx = true

[env]
# Directory paths
ROOT_DIR = "{{config_root}}"

[tools]
jq = '1.7.1'                            #renovate: packageName=jqlang/jq
kubectl = '1.32.3'                      #renovate: datasource=github-tags packageName=kubernetes/kubectl versioning=^kubernetes-(?<version>.*)$
kubeconform = '0.6.7'                   #renovate: packageName=yannh/kubeconform
kustomize = '5.6.0'                     #renovate: packageName=kubernetes-sigs/kustomize
stern = '1.32.0'                        #renovate: packageName=stern/stern  
"pipx:uv" = '0.6.10'                     #renovate: packageName=astral-sh/uv
go = '1.24.2'                           #renovate: datasource=golang-version packageName=golang/go
