apiVersion: v2
name: templated-secret-controller
description: A Helm chart for the Templated Secret Controller
type: application
version: 0.1.0
appVersion: "latest"
kubeVersion: ">=1.16.0-0"
home: https://github.com/drae/templated-secret-controller
sources:
  - https://github.com/drae/templated-secret-controller
keywords:
  - kubernetes
  - secrets
  - templating
maintainers:
  - name: starstreak.dev
    url: https://github.com/drae/
